// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_MasonNH.Models;

namespace Mission06_MasonNH.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_MasonNH.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            category = "Comedy",
                            director = "Akiva Schaffer",
                            edited = false,
                            rating = "PG-13",
                            title = "Hot Rod",
                            year = 2007
                        },
                        new
                        {
                            MovieId = 2,
                            category = "Family",
                            director = "Tom McGrath",
                            edited = false,
                            rating = "PG",
                            title = "Megamind",
                            year = 2010
                        },
                        new
                        {
                            MovieId = 3,
                            category = "Family",
                            director = "Brad Bird",
                            edited = false,
                            rating = "PG",
                            title = "The Incredibles",
                            year = 2004
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
